services:
  mariadb:
    image: mariadb:10.8
    restart: always
    environment:
      - MARIADB_USER=usuario
      - MARIADB_PASSWORD=senha
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=teste
    ports:
      - 3306:3306
